### ISSUE TITLE
인공지능 모델 데이터 전처리

### ISSUE THREAD

**Issue by suan073** [suan073/NEEDle_ideaBank#3]
### skip-gram의 학습을 위한 데이터 찾기

* 담당자
  * 김승준

* 데이터 
  * 위키피디아에서 제공해주는 한글 데이터 뭉치  

* 전처리 과정
  * (추가 바람)

**Comment by kimmokalover** [comment]
### skip-gram의 학습을 위한 데이터 찾기

* 담당자
  * 김승준

* 데이터 
  * 위키피디아에서 제공해주는 한글 데이터 뭉치  

* 전처리 과정
    - Parsing Program
    - 사용 언어: 파이썬
    - 사용 모듈 time
    - is_korean() : utf-8로 encoding된 한글 유니코드 판별해주는 함수
    - is_digit(): 숫자인지 판별해 주는 함수
    - get_textfile(): 함수 text 파일 디렉토리 내에 존재하는 파일들의 path 지정하는 함수
    - parsing() 함수: 한글, 숫자, \n, ‘ ‘, 그리고 괄호 사이에 있는 문장 지우는 Parsing 하는 함수
    - save_file()함수: AA~AJ 디랙토리에 wiki_xx.txt 형태로 텍스트 파일로 Parsing한 텍스트 저장.
