### ISSUE TITLE
모델 구현 및 학습

### ISSUE THREAD

**Issue by suan073** [suan073/NEEDle_ideaBank#4]
### skip-gram의 학습

* 바닐라 모델로 테스트 중
  * 사용 코드 출처
    * 밑바닥 부터 시작하는 딥러닝2의 실험 코드

  * 개선 사항
    * 나중에 학습이 잘 진행됨을 파악하면 파이토치 또는 텐서 플로우 등을 활용하여 모델을 재구성 할예정
    * @YunDamin 의 연구 사항을 반영하여 개선할 예정

**Comment by suan073** [comment]
### 문제 상황 발생

모델의 학습을 진행하기에 메모리가 부족함

→  코랩 pro를 구독하여 메모리 문제를 해결해보는 시도를 하기로 함

**Comment by kimmokalover** [comment]
### **k-means 클러스터링**
모델의 학습을 진행 하기 위해 군집화를 한 후 여러개의 모델에서 각각 학습할 예정
-> centroid 구할 때 에러 고침
