### ISSUE TITLE
깃허브 숙련도 올리기

### ISSUE THREAD

**Issue by suan073** [suan073/NEEDle_ideaBank#7]
## 숙련도를 올리기 위한 실습 (구글링 꼭 해보면서 하기!)

* git
- [ ] 0. 깃 명령어 "git status"로 현재 기록 및 추적하지 않은 파일명 확인 하기
- [ ] 1. 깃 명령어 "git add ~파일명~"으로  stage에 편집 사항을 추적 및 기록할 파일 추가하기
- [ ] 2. 깃 명령어 "git commit"로 stage에 올라간 파일들의 지금까지의 수정사항 기록하기
- [ ] 3. 깃 명령어 "git push"로 commit 한 기록들 및 stage의 파일들 깃허브(=원격 서버)에 올리기

* github
- [ ] 0. 깃 clone 해보기
- [ ] 1. project 구경 하기 → 프로젝트의 각 작업들은 이슈로 연결 될 수 있음을 이해하기
- [ ] 2. 이슈 구경해보기 → 이슈에 코멘트 달아보기 → 코멘트는 마크 다운이라는 문법으로 적을 수 있는데 간단하니 구글링 하면서 간단히 알아보기
- [ ] 3. 마일스톤 확인하기 → 마일스톤은 관련된 이슈들을 한번에 모아 볼 수 있도록 함.
- [ ] 3. 본인만의 이슈 만들어보기 → 생성한 이슈의 삭제는 레포지스토리 주인만 가능함 삭제하고자 하면 @suan073 에게 문의

( 아래 코멘트에 자신을 위한 체크 박스 만들고(복붙해도 됨) 자신의 진행사항 체크박스를 통해 표시하기)

**Comment by kimmokalover** [comment]
- git

- [ ] 0. 깃 명령어 "git status"로 현재 기록 및 추적하지 않은 파일명 확인 하기
- [ ] 1. 깃 명령어 "git add 파일명"으로 stage에 편집 사항을 추적 및 기록할 파일 추가하기
- [ ] 2. 깃 명령어 "git commit"로 stage에 올라간 파일들의 지금까지의 수정사항 기록하기
- [ ] 3. 깃 명령어 "git push"로 commit 한 기록들 및 stage의 파일들 깃허브(=원격 서버)에 올리기

- github
- [ ] 0. 깃 clone 해보기
- [ ] 1. project 구경 하기 → 프로젝트의 각 작업들은 이슈로 연결 될 수 있음을 이해하기
- [ ] 2. 이슈 구경해보기 → 이슈에 코멘트 달아보기 → 코멘트는 마크 다운이라는 문법으로 적을 수 있는데 간단하니 구글링 하면서 간단히 알아보기
- [ ] 3. 마일스톤 확인하기 → 마일스톤은 관련된 이슈들을 한번에 모아 볼 수 있도록 함.
- [ ] 3. 본인만의 이슈 만들어보기 → 생성한 이슈의 삭제는 레포지스토리 주인만 가능함 삭제하고자 하면 @suan073 에게 문의
