### ISSUE TITLE
colab에 깃허브 연동해보기

### ISSUE THREAD

**Issue by suan073** [suan073/NEEDle_ideaBank#8]
### colab을 통해 인공지능 모델의 학습을 진행할 것이므로 연동이 필요함

- [ ] colab & github 연동 해보기

- [ ] github의 코드 colab에서 동작시켜보기

- [ ] colab에서 깃허브에 commit 해보기

( 아래 코멘트에 자신을 위한 체크 박스 만들고(복붙해도 됨) 자신의 진행사항 체크박스를 통해 표시하기)

**Comment by suan073** [comment]
* 이수인 진행도

- [ ] colab & github 연동 해보기

- [ ] github의 코드 colab에서 동작시켜보기

- [ ] colab에서 깃허브에 commit 해보기

**Comment by kimmokalover** [comment]
- 김승준의 진행도

- [ ]  colab & github 연동 해보기
- [ ] github의 코드 colab에서 동작시켜보기
- [ ] colab에서 깃허브에 commit 해보기
